# Generated by Django 5.2.7 on 2025-10-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categorie",
            new_name="category",
        ),
    ]
